-- Keep the database enum in sync with prisma/schema.prisma.
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'BORRADOR';
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'ENVIADA';
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'PENDIENTE';
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'EN_AJUSTE';
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'RESERVADA';
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'REVISADA';
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'PAGADA';
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'VIAJE_REALIZADO';
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'RECHAZADA';
ALTER TYPE "Estado" ADD VALUE IF NOT EXISTS 'VENCIDA';

ALTER TABLE "cotizaciones" ALTER COLUMN "estado" SET DEFAULT 'BORRADOR';
